// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBydnr5lKvznznUjG9nFFIlaIDdjTN2h0A',
    appId: '1:861455554483:web:ffa83bca1d4a5ff9bd1dc6',
    messagingSenderId: '861455554483',
    projectId: 'test11-6744f',
    authDomain: 'test11-6744f.firebaseapp.com',
    storageBucket: 'test11-6744f.appspot.com',
    measurementId: 'G-0GSPDZ9801',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm3VTmEPCcgTIoUiVvakoIzyTZqiRVMck',
    appId: '1:861455554483:android:042fed47153d31d4bd1dc6',
    messagingSenderId: '861455554483',
    projectId: 'test11-6744f',
    storageBucket: 'test11-6744f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdaCoiq0DtJnGyG1CpuEBxUGpo_9EuabA',
    appId: '1:861455554483:ios:a5be2ce56e65d753bd1dc6',
    messagingSenderId: '861455554483',
    projectId: 'test11-6744f',
    storageBucket: 'test11-6744f.appspot.com',
    iosBundleId: 'com.example.test11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdaCoiq0DtJnGyG1CpuEBxUGpo_9EuabA',
    appId: '1:861455554483:ios:a5be2ce56e65d753bd1dc6',
    messagingSenderId: '861455554483',
    projectId: 'test11-6744f',
    storageBucket: 'test11-6744f.appspot.com',
    iosBundleId: 'com.example.test11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBydnr5lKvznznUjG9nFFIlaIDdjTN2h0A',
    appId: '1:861455554483:web:61729a0a2b24dfb4bd1dc6',
    messagingSenderId: '861455554483',
    projectId: 'test11-6744f',
    authDomain: 'test11-6744f.firebaseapp.com',
    storageBucket: 'test11-6744f.appspot.com',
    measurementId: 'G-YGQ65YS8P0',
  );

}